/* Generated By:JavaCC: Do not edit this line. E_POWER_XConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface E_POWER_XConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 5;
  /** RegularExpression Id. */
  int Let = 6;
  /** RegularExpression Id. */
  int Const = 7;
  /** RegularExpression Id. */
  int SQ = 8;
  /** RegularExpression Id. */
  int DQ = 9;
  /** RegularExpression Id. */
  int Func = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int ELSEIF = 13;
  /** RegularExpression Id. */
  int For = 14;
  /** RegularExpression Id. */
  int DO = 15;
  /** RegularExpression Id. */
  int While = 16;
  /** RegularExpression Id. */
  int Switch = 17;
  /** RegularExpression Id. */
  int CONTINUE = 18;
  /** RegularExpression Id. */
  int _DEFAULT = 19;
  /** RegularExpression Id. */
  int CASE = 20;
  /** RegularExpression Id. */
  int BREAK = 21;
  /** RegularExpression Id. */
  int Condition = 22;
  /** RegularExpression Id. */
  int Logic = 23;
  /** RegularExpression Id. */
  int LP = 24;
  /** RegularExpression Id. */
  int RP = 25;
  /** RegularExpression Id. */
  int LB = 26;
  /** RegularExpression Id. */
  int RB = 27;
  /** RegularExpression Id. */
  int TP = 28;
  /** RegularExpression Id. */
  int PLUS = 29;
  /** RegularExpression Id. */
  int MINUS = 30;
  /** RegularExpression Id. */
  int inc = 31;
  /** RegularExpression Id. */
  int dec = 32;
  /** RegularExpression Id. */
  int Return = 33;
  /** RegularExpression Id. */
  int VarName = 34;
  /** RegularExpression Id. */
  int String = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUM>",
    "\"let\"",
    "\"const\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"function\"",
    "\"if\"",
    "\"else\"",
    "\"elseif\"",
    "\"for\"",
    "\"do\"",
    "\"while\"",
    "\"switch\"",
    "\"continue\"",
    "\"default\"",
    "\"case\"",
    "\"break\"",
    "<Condition>",
    "<Logic>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"++\"",
    "\"--\"",
    "\"return\"",
    "<VarName>",
    "<String>",
    "\";\"",
    "\"+=\"",
    "\"-=\"",
    "\",\"",
    "\", \"",
    "\"=\"",
  };

}
