/* Generated By:JavaCC: Do not edit this line. MoazConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MoazConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int SUB = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIV = 8;
  /** RegularExpression Id. */
  int LOG = 9;
  /** RegularExpression Id. */
  int SIN = 10;
  /** RegularExpression Id. */
  int COS = 11;
  /** RegularExpression Id. */
  int TAN = 12;
  /** RegularExpression Id. */
  int ABS = 13;
  /** RegularExpression Id. */
  int POWER = 14;
  /** RegularExpression Id. */
  int Fact = 15;
  /** RegularExpression Id. */
  int LOGICAL = 16;
  /** RegularExpression Id. */
  int ASSIGN = 17;
  /** RegularExpression Id. */
  int SEMI = 18;
  /** RegularExpression Id. */
  int COLON = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int FOR = 22;
  /** RegularExpression Id. */
  int ARROW = 23;
  /** RegularExpression Id. */
  int WHILE = 24;
  /** RegularExpression Id. */
  int READ = 25;
  /** RegularExpression Id. */
  int PRINT = 26;
  /** RegularExpression Id. */
  int VAR_ = 27;
  /** RegularExpression Id. */
  int LP = 28;
  /** RegularExpression Id. */
  int RP = 29;
  /** RegularExpression Id. */
  int LB = 30;
  /** RegularExpression Id. */
  int RB = 31;
  /** RegularExpression Id. */
  int NUM = 32;
  /** RegularExpression Id. */
  int VAR = 33;
  /** RegularExpression Id. */
  int INCR = 34;
  /** RegularExpression Id. */
  int DECR = 35;
  /** RegularExpression Id. */
  int PLUSASSIGN = 36;
  /** RegularExpression Id. */
  int MINUSASSIGN = 37;
  /** RegularExpression Id. */
  int MULTASSIGN = 38;
  /** RegularExpression Id. */
  int DIVASSIGN = 39;
  /** RegularExpression Id. */
  int REMASSIGN = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"log\"",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"abs\"",
    "\"**\"",
    "\"!\"",
    "<LOGICAL>",
    "\"=\"",
    "\";\"",
    "\":\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"->\"",
    "\"while\"",
    "\">>\"",
    "<PRINT>",
    "\"var\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<NUM>",
    "<VAR>",
    "\"++\"",
    "\"--\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\",\"",
  };

}
